export const FETCH_ALL_COURSES = 'FETCH_ALL_COURSES';
export const FETCH_APPROVED_COURSES = 'FETCH_ALL_COURSES';
export const SAVE_COURSE = 'SAVE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const APPROVE_COURSE = 'APPROVE_COURSE';
